import Link from 'next/link';
import { BackendCard } from '@/components/BackendCard';
import { CondensedComparisonTable } from '@/components/CondensedComparisonTable';
import { backends, educationalContent } from '@/lib/backends';

export default function HomePage() {

  return (
    <div>
      {/* Hero Section */}
      <section className="border-b border-neutral-200 dark:border-neutral-800">
        <div className="container-page py-20 md:py-28">
          <div className="max-w-3xl">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
              Find the best game backend{' '}
              <span className="text-primary-500">for your game</span>
            </h1>
            <p className="text-lg md:text-xl text-neutral-600 dark:text-neutral-400 mb-8 leading-relaxed">
              Compare game backend platforms side-by-side. Understand what you need,
              see how game backends stack up, and make the right choice for your project.
            </p>
            <div className="flex flex-col sm:flex-row gap-3">
              <Link href="/backends" className="btn-primary text-center">
                Compare Backends
              </Link>
              <Link href="#why-backend" className="btn-secondary text-center">
                Why Do I Need a Game Backend?
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Why Do You Need a Backend? */}
      <section id="why-backend" className="container-page py-16 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Why do you need a game backend?</h2>
          <p className="text-lg text-neutral-600 dark:text-neutral-400">
            The most successful games today are operated as <strong className="text-neutral-900 dark:text-neutral-100">live services</strong>,
            continuously updated, optimised, and evolved based on player data and engagement.
            You need a proper backend to handle this for you so you can focus on making the game, and not the tech.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-12">
          <div className="text-center">
            <div className="text-4xl font-bold text-primary-500 mb-2">84%</div>
            <p className="text-neutral-600 dark:text-neutral-400">
              of mobile game IAP revenue comes from games with Live Ops
            </p>
            <a href="https://sensortower.com/blog/state-of-mobile-gaming-2025" target="_blank" rel="noopener noreferrer" className="text-xs text-neutral-400 hover:text-primary-500 mt-1 inline-block">
              Source: Sensor Tower 2025
            </a>
          </div>
          <div className="text-center">
            <div className="text-4xl font-bold text-primary-500 mb-2">64%</div>
            <p className="text-neutral-600 dark:text-neutral-400">
              of F2P game revenue generated by top 10% of paying players
            </p>
            <a href="https://www.gamedeveloper.com/business/report-whales-gobble-up-even-more-of-the-f2p-mobile-game-revenue-pie" target="_blank" rel="noopener noreferrer" className="text-xs text-neutral-400 hover:text-primary-500 mt-1 inline-block">
              Source: Game Developer
            </a>
          </div>
          <div className="text-center">
            <div className="text-4xl font-bold text-primary-500 mb-2">12+</div>
            <p className="text-neutral-600 dark:text-neutral-400">
              years of revenue from top live service games like Clash of Clans
            </p>
            <a href="https://www.pocketgamer.biz/feature/66339/the-mobile-games-that-have-made-more-than-1-billion-in-lifetime-sales-update/" target="_blank" rel="noopener noreferrer" className="text-xs text-neutral-400 hover:text-primary-500 mt-1 inline-block">
              Source: PocketGamer.biz
            </a>
          </div>
        </div>

        <div className="card p-8 max-w-3xl mx-auto">
          <p className="text-neutral-600 dark:text-neutral-400 leading-relaxed">
            A game backend is the infrastructure that makes live service possible. Game backends handle
            player accounts, save progress to the cloud, manage your game economy, deliver
            live events, track analytics, and enable everything that keeps players engaged
            long after launch.
          </p>
          <p className="text-neutral-600 dark:text-neutral-400 leading-relaxed mt-4">
            Without a proper game backend, you&apos;re limited to single-player experiences or
            building everything from scratch. With the right game backend, you can focus on
            making a great game while the infrastructure handles the rest.
          </p>
        </div>
      </section>

      {/* What is Live Service? */}
      <section className="border-y border-neutral-200 dark:border-neutral-800">
        <div className="container-page py-16 md:py-20">
          <div className="max-w-3xl mx-auto text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">What does &quot;live service&quot; mean?</h2>
            <p className="text-lg text-neutral-600 dark:text-neutral-400">
              A live service game is designed to evolve over time, keeping players engaged
              through regular updates, events, and new content.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
            <div className="card p-6">
              <div className="w-10 h-10 rounded-md bg-primary-500/10 flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
              </div>
              <h3 className="font-medium mb-2">Ongoing Updates</h3>
              <p className="text-neutral-600 dark:text-neutral-400 text-sm">
                New content, features, and improvements delivered regularly to keep the game fresh.
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 rounded-md bg-primary-500/10 flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="font-medium mb-2">Live Events</h3>
              <p className="text-neutral-600 dark:text-neutral-400 text-sm">
                Time-limited events, seasons, and special occasions that create urgency and excitement.
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 rounded-md bg-primary-500/10 flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <h3 className="font-medium mb-2">Data-Driven</h3>
              <p className="text-neutral-600 dark:text-neutral-400 text-sm">
                Analytics and A/B testing to understand players and optimize the experience.
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 rounded-md bg-primary-500/10 flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="font-medium mb-2">Sustainable Revenue</h3>
              <p className="text-neutral-600 dark:text-neutral-400 text-sm">
                Ongoing monetization through battle passes, cosmetics, and in-app purchases.
              </p>
            </div>
          </div>

          <div className="text-center">
            <Link href="/learn/what-is-live-service" className="btn-secondary">
              Learn More About Live Service Games
            </Link>
          </div>
        </div>
      </section>

      {/* What a Backend Provides */}
      <section className="container-page py-16 md:py-20">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">What a game backend gives you</h2>
          <p className="text-lg text-neutral-600 dark:text-neutral-400">
            The right game backend platform provides the tools and infrastructure to run
            your game as a successful live service.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          <FeatureBlock
            title="Player Management"
            items={['Authentication & accounts', 'Cloud save & progression', 'Player segmentation']}
          />
          <FeatureBlock
            title="Live Operations"
            items={['Remote config & updates', 'Live events & seasons', 'A/B testing']}
          />
          <FeatureBlock
            title="Economy & Monetization"
            items={['Virtual currencies', 'Inventory & items', 'IAP & offers']}
          />
          <FeatureBlock
            title="Engagement"
            items={['Leaderboards', 'Achievements', 'Social features']}
          />
          <FeatureBlock
            title="Analytics"
            items={['Player behavior tracking', 'Revenue analytics', 'Custom dashboards']}
          />
          <FeatureBlock
            title="Infrastructure"
            items={['Global scaling', 'Multiplayer support', 'Admin tools']}
          />
        </div>
      </section>

      {/* Game Backends */}
      <section className="container-page py-16 md:py-20">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h2 className="text-2xl md:text-3xl font-bold">Game Backends</h2>
            <p className="text-neutral-600 dark:text-neutral-400 mt-2">
              Compare game backend platforms for live service games
            </p>
          </div>
          <Link
            href="/backends"
            className="hidden md:inline-flex text-sm text-neutral-500 hover:text-primary-500 transition-colors"
          >
            View all →
          </Link>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {backends.map((backend) => (
            <BackendCard key={backend.slug} backend={backend} />
          ))}
        </div>
      </section>

      {/* Quick Comparison Table */}
      <section className="border-y border-neutral-200 dark:border-neutral-800">
        <div className="container-page py-16 md:py-20">
          <div className="max-w-3xl mx-auto text-center mb-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">Quick Comparison</h2>
            <p className="text-neutral-600 dark:text-neutral-400">
              See how game backends stack up across key feature categories.
              Hover over &quot;Many&quot; or &quot;Some&quot; to see which features are supported.
            </p>
          </div>
          <div className="card p-6">
            <CondensedComparisonTable />
          </div>
          <div className="text-center mt-8">
            <Link href="/backends" className="btn-primary">
              View Full Comparison
            </Link>
          </div>
        </div>
      </section>

      {/* Learn More */}
      <section className="container-page py-16 md:py-20">
        <div className="text-center mb-12">
          <h2 className="text-2xl md:text-3xl font-bold">Want to learn more?</h2>
          <p className="text-neutral-600 dark:text-neutral-400 mt-2">
            Dive deeper into live service game operations
          </p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {educationalContent.slice(0, 3).map((content) => (
            <Link
              key={content.slug}
              href={`/learn/${content.slug}`}
              className="card p-6 hover:border-primary-500/50 transition-colors group"
            >
              <h3 className="font-medium mb-2 group-hover:text-primary-500 transition-colors flex items-center gap-2">
                <GuideIcon slug={content.slug} />
                {content.title}
              </h3>
              <p className="text-neutral-600 dark:text-neutral-400 text-sm">
                {content.description}
              </p>
            </Link>
          ))}
        </div>
        <div className="text-center mt-8">
          <Link href="/learn" className="btn-secondary">
            View All Guides
          </Link>
        </div>
      </section>
    </div>
  );
}

function FeatureBlock({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="card p-6">
      <h3 className="font-medium mb-3">{title}</h3>
      <ul className="space-y-2">
        {items.map((item, index) => (
          <li key={index} className="flex items-center gap-2 text-neutral-600 dark:text-neutral-400 text-sm">
            <svg className="w-4 h-4 text-primary-500 shrink-0" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
            </svg>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

function GuideIcon({ slug }: { slug: string }) {
  const iconClass = "w-5 h-5 text-primary-500 shrink-0";

  switch (slug) {
    case 'what-is-live-service':
      // Rocket icon
      return (
        <svg className={iconClass} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.448 14.9 14.9 0 01.06-.312m-2.24 2.39a4.493 4.493 0 00-1.757 4.306 4.493 4.493 0 004.306-1.758M16.5 9a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z" />
        </svg>
      );
    case 'pillars-of-live-ops':
      // Building columns icon
      return (
        <svg className={iconClass} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
        </svg>
      );
    case 'retention-engagement':
      // Users/people icon
      return (
        <svg className={iconClass} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
      );
    default:
      // Default book icon
      return (
        <svg className={iconClass} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
        </svg>
      );
  }
}
