import { Backend, Category, GameType, LiveOpsFeatures } from './types';

export type { Backend, Category, GameType, LiveOpsFeatures } from './types';

export const backends: Backend[] = [
  {
    slug: 'metaplay',
    name: 'Metaplay',
    tagline: 'Purpose-built backend platform for live service games',
    description: 'Metaplay is a comprehensive game backend platform specifically designed for live service games. It provides a complete suite of tools for player management, live operations, game economy, and analytics - everything studios need to run successful games-as-a-service. Built by game industry veterans, Metaplay emphasizes both developer experience and operational excellence.',
    logo: '/images/metaplay.svg',
    website: 'https://metaplay.io',
    docsUrl: 'https://docs.metaplay.io',
    type: 'full-platform',
    pricingModel: 'freemium',
    pricingDetails: 'Free for local development. Starter €195/month (5 DAU), Pre-Launch €995/month, Production €1,985/month+.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['F2P mobile games', 'Live service RPGs', 'Strategy games', 'Games with complex economies'],
    gameTypes: ['f2p-mobile', 'live-service-pc', 'casual-social'],
    platforms: ['unity', 'custom'],
    strengths: [
      'Purpose-built for live service game operations',
      'Full source code access - deploy to your own cloud',
      'Comprehensive game economy and monetization tools',
      'Built-in admin dashboard for live ops teams',
      'Strong player segmentation and targeting',
    ],
    limitations: [
      'Unity-only SDK (no Unreal support)',
      'Not designed for real-time competitive multiplayer',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2019,
    lastUpdated: '2025-01',
  },
  {
    slug: 'playfab',
    name: 'PlayFab',
    tagline: 'Microsoft\'s backend platform for live games',
    description: 'PlayFab is a comprehensive backend platform for building and operating live games, now part of Microsoft\'s Azure Gaming ecosystem. It offers a wide range of services from player authentication to live ops and analytics, with deep integration into Azure cloud services.',
    logo: '/images/playfab.svg',
    website: 'https://playfab.com',
    docsUrl: 'https://learn.microsoft.com/en-us/gaming/playfab/',
    type: 'full-platform',
    pricingModel: 'usage-based',
    pricingDetails: 'Free development mode (100K accounts). Consumption-based pricing: Standard $99/month, Premium $1,999/month.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: false,
    },
    bestFor: ['Indie to mid-size studios', 'Xbox/PC games', 'Studios already in Azure ecosystem'],
    gameTypes: ['f2p-mobile', 'live-service-pc', 'competitive', 'casual-social'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    strengths: [
      'Generous free tier for smaller games',
      'Deep Azure and Xbox integration',
      'Broad SDK support across engines',
      'Extensive documentation',
      'Multiplayer server hosting included',
    ],
    limitations: [
      'Advanced features require Azure subscription',
      'Original team departed post-acquisition (2022)',
      'Some documentation gaps reported post-acquisition',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'nakama',
    name: 'Nakama',
    tagline: 'Open-source scalable game server',
    description: 'Nakama is an open-source distributed game server by Heroic Labs that handles authentication, social features, storage, and real-time multiplayer. It can be self-hosted or used via their managed cloud service, offering flexibility for studios that want control over their infrastructure.',
    logo: '/images/nakama.svg',
    website: 'https://heroiclabs.com/nakama/',
    docsUrl: 'https://heroiclabs.com/docs/nakama/',
    githubUrl: 'https://github.com/heroiclabs/nakama',
    type: 'open-source',
    pricingModel: 'freemium',
    pricingDetails: 'Apache 2.0 open source (free self-hosting). Heroic Cloud managed service from $600/month.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: true,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: false,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: true,
      analytics: false,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Studios wanting infrastructure control', 'Real-time multiplayer games', 'Teams with DevOps capability'],
    gameTypes: ['competitive', 'casual-social', 'f2p-mobile'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    strengths: [
      'Open source with active development',
      'Strong real-time multiplayer capabilities',
      'Flexible self-hosting or managed options',
      'Good SDK support across platforms',
      'Active community',
    ],
    limitations: [
      'Managed cloud minimum $600/month (expensive for indie)',
      'Multi-server clustering requires Enterprise license',
      'Self-hosting requires DevOps expertise',
      'No built-in CMS for game content',
    ],
    liveServiceFit: 'partial',
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'aws-gamelift',
    name: 'AWS GameLift',
    tagline: 'Dedicated game server hosting from Amazon',
    description: 'Amazon GameLift is a dedicated game server hosting and matchmaking service - NOT a full backend-as-a-service. It excels at deploying and scaling game servers for session-based multiplayer, but requires additional AWS services or third-party solutions for player data, economy, and live ops.',
    logo: '/images/gamelift.svg',
    website: 'https://aws.amazon.com/gamelift/',
    docsUrl: 'https://docs.aws.amazon.com/gamelift/',
    type: 'partial-solution',
    pricingModel: 'usage-based',
    pricingDetails: 'Pay per instance hour (e.g., c5.large ~$0.11/hr). Free tier: 125 hours/month for 12 months. Spot instances 50-85% cheaper.',
    features: {
      authentication: false,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Session-based multiplayer', 'Games needing dedicated servers', 'Studios in AWS ecosystem'],
    gameTypes: ['competitive', 'mmo'],
    platforms: ['unity', 'unreal', 'godot', 'custom'],
    strengths: [
      'Enterprise-grade server infrastructure',
      'Excellent auto-scaling for player demand',
      'FlexMatch offers flexible matchmaking',
      'Global presence across AWS regions',
      'Deep AWS service integration',
    ],
    limitations: [
      'Server hosting only - not a complete backend',
      'Requires building other live service features separately',
      'Steep learning curve for AWS newcomers',
      'No player management or economy features',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2016,
    lastUpdated: '2025-01',
  },
  {
    slug: 'photon-engine',
    name: 'Photon Engine',
    tagline: 'Real-time multiplayer networking platform',
    description: 'Photon is a suite of products for real-time multiplayer games, including Photon Cloud, Photon Server, and Photon Fusion. It focuses on networking and synchronization, providing reliable real-time communication for games.',
    logo: '/images/photon.svg',
    website: 'https://www.photonengine.com',
    docsUrl: 'https://doc.photonengine.com',
    type: 'partial-solution',
    pricingModel: 'usage-based',
    pricingDetails: 'Free: 100 CCU (Fusion/Quantum) or 20 CCU (legacy). CCU-based plans from $95/year to enterprise.',
    features: {
      authentication: true,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Real-time multiplayer games', 'Unity developers', 'Games needing low-latency networking'],
    gameTypes: ['competitive', 'casual-social'],
    platforms: ['unity', 'unreal', 'custom', 'html5'],
    strengths: [
      'Industry-leading real-time networking',
      'Excellent Unity integration',
      'Photon Fusion for advanced networking',
      'Reliable global infrastructure',
      'Well-documented with tutorials',
    ],
    limitations: [
      'No player data persistence (rooms deleted after players leave)',
      'No leaderboards, inventory, economy, or live ops',
      'Unreal support is C++ only (no Blueprints)',
      'Requires separate backend for player management',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2003,
    lastUpdated: '2025-01',
  },
  {
    slug: 'unity-gaming-services',
    name: 'Unity Gaming Services',
    tagline: 'Backend services integrated into Unity',
    description: 'Unity Gaming Services (UGS) is Unity\'s suite of backend services with tight editor integration. Provides auth, cloud save, economy, analytics, and more. Note: Multiplay server hosting is shutting down March 2026; company underwent significant layoffs in 2024.',
    logo: '/images/unity.svg',
    website: 'https://unity.com/solutions/gaming-services',
    docsUrl: 'https://docs.unity.com/ugs/',
    type: 'full-platform',
    pricingModel: 'usage-based',
    pricingDetails: 'Free tier available. Usage-based pricing for higher volumes.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: false,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: false,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: false,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Unity-focused studios', 'Teams wanting tight editor integration', 'Rapid prototyping'],
    gameTypes: ['f2p-mobile', 'casual-social', 'competitive'],
    platforms: ['unity', 'unreal'],
    strengths: [
      'Seamless Unity editor integration',
      'Unified dashboard for all services',
      'Good analytics and A/B testing',
      'Economy system included',
      'Active development and expansion',
    ],
    limitations: [
      'Multiplay server hosting shutting down March 2026',
      'Limited data portability guarantees',
      'Stability concerns after 25% workforce layoffs (2024)',
      'Vendor lock-in to Unity ecosystem',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2021,
    lastUpdated: '2025-01',
  },
  {
    slug: 'colyseus',
    name: 'Colyseus',
    tagline: 'Multiplayer game server framework for Node.js',
    description: 'Colyseus is an authoritative multiplayer game server framework for Node.js. It provides state synchronization, matchmaking, and room-based multiplayer with a focus on simplicity and developer experience for building real-time games.',
    logo: '/images/colyseus.svg',
    website: 'https://colyseus.io',
    docsUrl: 'https://docs.colyseus.io',
    githubUrl: 'https://github.com/colyseus/colyseus',
    type: 'open-source',
    pricingModel: 'free',
    pricingDetails: 'MIT License, fully open source. Colyseus Cloud offers managed hosting (tiered pricing).',
    features: {
      authentication: true,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: false,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: false,
      globalScaling: false,
      adminDashboard: false,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Indie developers', 'Rapid multiplayer prototyping', 'Node.js/TypeScript developers'],
    gameTypes: ['casual-social', 'competitive'],
    platforms: ['unity', 'custom', 'html5'],
    strengths: [
      'Easy to learn and quick to prototype',
      'Excellent state synchronization',
      'Active open-source community',
      'Full control over server logic',
      'Free to use',
    ],
    limitations: [
      'No Unreal Engine support',
      'No built-in persistence (requires external database)',
      'No live ops, leaderboards, analytics, or economy',
      'Smaller community (~3K Discord, ~6.5K GitHub stars)',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2015,
    lastUpdated: '2025-01',
  },
  {
    slug: 'braincloud',
    name: 'brainCloud',
    tagline: 'Backend-as-a-service for games',
    description: 'brainCloud is a ready-made backend platform for games that provides a comprehensive set of cloud features including player management, cloud data, leaderboards, and multiplayer support with a focus on mobile and casual games.',
    logo: '/images/braincloud.svg',
    website: 'https://getbraincloud.com',
    docsUrl: 'https://docs.braincloudservers.com',
    type: 'full-platform',
    pricingModel: 'freemium',
    pricingDetails: 'Free tier (100 DAU). API-based pricing: Lite $15/month, Standard $30/month, Business $99-199/month.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: false,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['Mobile games', 'Casual games', 'Small to mid-size studios'],
    gameTypes: ['f2p-mobile', 'casual-social'],
    platforms: ['unity', 'unreal', 'godot', 'custom'],
    strengths: [
      'Comprehensive feature set',
      'Good for mobile game development',
      'Achievements and gamification built-in',
      'Reasonable pricing for smaller games',
      'Long-established platform',
    ],
    limitations: [
      'Steeper learning curve due to feature complexity',
      'Smaller community than PlayFab/Nakama',
      'API rate limits apply (check documentation)',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'accelbyte',
    name: 'AccelByte',
    tagline: 'Backend platform for AAA live service games',
    description: 'AccelByte provides a comprehensive backend platform targeting AAA and large-scale live service games. It offers player identity, social features, e-commerce, game services, and analytics designed for high-scale productions.',
    logo: '/images/accelbyte.svg',
    website: 'https://accelbyte.io',
    docsUrl: 'https://docs.accelbyte.io',
    type: 'full-platform',
    pricingModel: 'freemium',
    pricingDetails: 'Free up to 25K play hours. Foundations $100/month (shared cloud). Enterprise pricing for dedicated environments.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['AAA studios', 'Large-scale live service games', 'Cross-platform titles'],
    gameTypes: ['live-service-pc', 'competitive', 'mmo'],
    platforms: ['unity', 'unreal', 'custom'],
    strengths: [
      'Built for AAA scale',
      'Comprehensive feature coverage',
      'Strong e-commerce and monetization',
      'Cross-platform support',
      'Enterprise-grade infrastructure',
    ],
    limitations: [
      'Enterprise (dedicated) pricing requires contacting sales',
      'Feature-rich platform requires learning investment',
      'Foundations tier may have feature limitations',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2016,
    lastUpdated: '2025-01',
  },
];

export const categories: Category[] = [
  {
    slug: 'f2p-mobile',
    name: 'F2P Mobile Games',
    description: 'Free-to-play mobile games that rely on live ops, events, and monetization to drive revenue and retention.',
    gameTypes: ['f2p-mobile'],
  },
  {
    slug: 'live-service-pc',
    name: 'Live Service PC/Console',
    description: 'PC and console games operated as ongoing services with regular content updates and seasonal events.',
    gameTypes: ['live-service-pc'],
  },
  {
    slug: 'competitive',
    name: 'Competitive Multiplayer',
    description: 'Competitive games requiring real-time multiplayer, matchmaking, and ranking systems.',
    gameTypes: ['competitive'],
  },
  {
    slug: 'casual-social',
    name: 'Casual & Social Games',
    description: 'Casual games with social features, leaderboards, and lighter live ops requirements.',
    gameTypes: ['casual-social'],
  },
  {
    slug: 'mmo',
    name: 'MMO & Persistent Worlds',
    description: 'Massively multiplayer games requiring large-scale infrastructure and persistent world states.',
    gameTypes: ['mmo'],
  },
];

export const educationalContent = [
  {
    slug: 'what-is-live-service',
    title: 'What is a Live Service Game?',
    description: 'Understanding the live service model and why it dominates modern game development.',
    order: 1,
  },
  {
    slug: 'pillars-of-live-ops',
    title: 'Pillars of Live Operations',
    description: 'The core capabilities every live service game needs to succeed.',
    order: 2,
  },
  {
    slug: 'retention-engagement',
    title: 'Retention & Engagement',
    description: 'Strategies and features that keep players coming back day after day.',
    order: 3,
  },
  {
    slug: 'monetization-economy',
    title: 'Monetization & Game Economy',
    description: 'Building sustainable revenue through virtual economies and in-app purchases.',
    order: 4,
  },
  {
    slug: 'analytics-optimization',
    title: 'Analytics & Optimization',
    description: 'Using data to understand player behavior and optimize your game.',
    order: 5,
  },
];

export function getBackendBySlug(slug: string): Backend | undefined {
  return backends.find(b => b.slug === slug);
}

export function getBackendsByGameType(gameType: GameType): Backend[] {
  return backends.filter(b => b.gameTypes.includes(gameType));
}

export function getBackendsByType(type: Backend['type']): Backend[] {
  return backends.filter(b => b.type === type);
}

export function getBackendsByLiveServiceFit(fit: Backend['liveServiceFit']): Backend[] {
  return backends.filter(b => b.liveServiceFit === fit);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug);
}

export function getAllSlugs(): string[] {
  return backends.map(b => b.slug);
}

export const featureCategories = {
  'Player Management': ['authentication', 'playerProfiles', 'playerSegmentation'],
  'Live Operations': ['liveEvents', 'seasonalContent', 'remoteConfig', 'abTesting', 'scheduledContent'],
  'Economy & Monetization': ['virtualCurrency', 'inventorySystem', 'iapValidation', 'offers'],
  'Engagement & Retention': ['pushNotifications', 'leaderboards', 'achievements', 'socialFeatures', 'guildsClans'],
  'Analytics & Insights': ['analytics', 'playerBehaviorTracking', 'revenueAnalytics', 'customDashboards'],
  'Multiplayer & Real-time': ['multiplayer', 'matchmaking', 'chat'],
  'Infrastructure': ['cloudSave', 'serverlessLogic', 'dedicatedServers', 'globalScaling'],
  'Operations': ['adminDashboard', 'playerSupport', 'moderation'],
};

export const featureLabels: Record<keyof LiveOpsFeatures, string> = {
  authentication: 'Authentication',
  playerProfiles: 'Player Profiles',
  playerSegmentation: 'Player Segmentation',
  liveEvents: 'Live Events',
  seasonalContent: 'Seasonal Content',
  remoteConfig: 'Remote Config',
  abTesting: 'A/B Testing',
  scheduledContent: 'Scheduled Content',
  virtualCurrency: 'Virtual Currency',
  inventorySystem: 'Inventory System',
  iapValidation: 'IAP Validation',
  offers: 'Targeted Offers',
  pushNotifications: 'Push Notifications',
  leaderboards: 'Leaderboards',
  achievements: 'Achievements',
  socialFeatures: 'Social Features',
  guildsClans: 'Guilds/Clans',
  analytics: 'Analytics',
  playerBehaviorTracking: 'Behavior Tracking',
  revenueAnalytics: 'Revenue Analytics',
  customDashboards: 'Custom Dashboards',
  multiplayer: 'Multiplayer',
  matchmaking: 'Matchmaking',
  chat: 'Chat',
  cloudSave: 'Cloud Save',
  serverlessLogic: 'Serverless Logic',
  dedicatedServers: 'Dedicated Servers',
  globalScaling: 'Global Scaling',
  adminDashboard: 'Admin Dashboard',
  playerSupport: 'Player Support Tools',
  moderation: 'Moderation',
};

export const typeLabels: Record<Backend['type'], string> = {
  'full-platform': 'Full Platform',
  'partial-solution': 'Partial Solution',
  'open-source': 'Open Source',
};

export const pricingLabels: Record<Backend['pricingModel'], string> = {
  'free': 'Free',
  'freemium': 'Freemium',
  'usage-based': 'Usage-Based',
  'enterprise': 'Enterprise',
};

export const liveServiceFitLabels: Record<Backend['liveServiceFit'], string> = {
  'comprehensive': 'Comprehensive',
  'partial': 'Partial Coverage',
  'minimal': 'Networking Only',
};
