import { Backend, Category, UseCase } from './types';

export type { Backend, Category, UseCase } from './types';

export const backends: Backend[] = [
  {
    slug: 'playfab',
    name: 'PlayFab',
    tagline: 'Microsoft\'s complete backend platform for live games',
    description: 'PlayFab is a comprehensive backend platform for building and operating live games, offering a wide range of services from player authentication to live ops and analytics. As part of Microsoft\'s Azure ecosystem, it provides enterprise-grade reliability and scalability.',
    logo: '/images/playfab.svg',
    website: 'https://playfab.com',
    docsUrl: 'https://learn.microsoft.com/en-us/gaming/playfab/',
    type: 'commercial',
    pricingModel: 'freemium',
    pricingDetails: 'Free tier up to 100K MAU. Pay-as-you-go pricing above.',
    features: {
      matchmaking: true,
      leaderboards: true,
      cloudSave: true,
      analytics: true,
      multiplayer: true,
      serverless: true,
      authentication: true,
      chat: false,
      pushNotifications: true,
      inventory: true,
      economy: true,
      tournaments: true,
    },
    useCases: ['mobile', 'indie', 'competitive', 'casual'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    pros: [
      'Generous free tier for indie developers',
      'Deep Azure integration',
      'Comprehensive documentation',
      'Built-in economy and virtual currency systems',
      'Strong analytics and A/B testing',
    ],
    cons: [
      'Can become expensive at scale',
      'Learning curve for advanced features',
      'Some features require Azure knowledge',
    ],
    rating: 4.2,
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'aws-gamelift',
    name: 'AWS GameLift',
    tagline: 'Dedicated game server hosting from Amazon Web Services',
    description: 'Amazon GameLift is a dedicated game server hosting solution that deploys, operates, and scales cloud servers for multiplayer games. It offers FlexMatch for matchmaking and integrates seamlessly with other AWS services.',
    logo: '/images/gamelift.svg',
    website: 'https://aws.amazon.com/gamelift/',
    docsUrl: 'https://docs.aws.amazon.com/gamelift/',
    type: 'commercial',
    pricingModel: 'paid',
    pricingDetails: 'Pay per instance hour. FlexMatch has separate pricing.',
    features: {
      matchmaking: true,
      leaderboards: false,
      cloudSave: false,
      analytics: true,
      multiplayer: true,
      serverless: false,
      authentication: false,
      chat: false,
      pushNotifications: false,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['mmo', 'competitive', 'casual'],
    platforms: ['unity', 'unreal', 'custom'],
    pros: [
      'Enterprise-grade infrastructure',
      'Excellent auto-scaling capabilities',
      'FlexMatch is highly flexible',
      'Global reach with multiple regions',
      'Deep AWS ecosystem integration',
    ],
    cons: [
      'Steep learning curve',
      'Requires significant AWS knowledge',
      'Focused mainly on server hosting, not full backend',
      'No free tier for production use',
    ],
    rating: 4.0,
    foundedYear: 2016,
    lastUpdated: '2025-01',
  },
  {
    slug: 'google-cloud-gaming',
    name: 'Google Cloud for Games',
    tagline: 'Google\'s suite of game development tools and infrastructure',
    description: 'Google Cloud for Games provides infrastructure and services tailored for game developers, including Open Match for matchmaking, Agones for Kubernetes-based game servers, and integration with Google Play services.',
    logo: '/images/google-cloud.svg',
    website: 'https://cloud.google.com/solutions/gaming',
    docsUrl: 'https://cloud.google.com/docs/gaming',
    type: 'commercial',
    pricingModel: 'paid',
    pricingDetails: 'Pay-as-you-go based on resource usage.',
    features: {
      matchmaking: true,
      leaderboards: true,
      cloudSave: true,
      analytics: true,
      multiplayer: true,
      serverless: true,
      authentication: true,
      chat: false,
      pushNotifications: true,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['mmo', 'mobile', 'competitive'],
    platforms: ['unity', 'unreal', 'custom'],
    pros: [
      'Open Match is open-source and flexible',
      'Great for Kubernetes-native workflows',
      'Strong data analytics with BigQuery',
      'Google Play Games integration for mobile',
    ],
    cons: [
      'Not a unified solution - requires assembling services',
      'Can be complex to set up',
      'Less gaming-specific documentation than competitors',
    ],
    rating: 3.8,
    foundedYear: 2019,
    lastUpdated: '2025-01',
  },
  {
    slug: 'photon-engine',
    name: 'Photon Engine',
    tagline: 'Real-time multiplayer game development platform',
    description: 'Photon is a suite of products for real-time multiplayer games, including Photon Cloud, Photon Server, and Photon Fusion. Known for its ease of use and reliable networking, it\'s popular among Unity developers.',
    logo: '/images/photon.svg',
    website: 'https://www.photonengine.com',
    docsUrl: 'https://doc.photonengine.com',
    type: 'commercial',
    pricingModel: 'freemium',
    pricingDetails: 'Free tier with 20 CCU. Subscription plans based on CCU.',
    features: {
      matchmaking: true,
      leaderboards: false,
      cloudSave: false,
      analytics: true,
      multiplayer: true,
      serverless: true,
      authentication: true,
      chat: true,
      pushNotifications: false,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['indie', 'competitive', 'casual', 'mobile'],
    platforms: ['unity', 'unreal', 'custom', 'html5'],
    pros: [
      'Excellent Unity integration',
      'Low latency networking',
      'Photon Fusion offers advanced features',
      'Well-documented with many tutorials',
      'Generous free tier for prototyping',
    ],
    cons: [
      'CCU-based pricing can be unpredictable',
      'Limited backend services beyond networking',
      'Self-hosted option requires more work',
    ],
    rating: 4.3,
    foundedYear: 2004,
    lastUpdated: '2025-01',
  },
  {
    slug: 'metaplay',
    name: 'Metaplay',
    tagline: 'Game backend platform built for live service games',
    description: 'Metaplay is a backend platform specifically designed for live service games, offering features like player management, economy systems, and real-time analytics. It emphasizes customizability while providing production-ready infrastructure.',
    logo: '/images/metaplay.svg',
    website: 'https://metaplay.io',
    docsUrl: 'https://docs.metaplay.io',
    type: 'commercial',
    pricingModel: 'enterprise',
    pricingDetails: 'Custom pricing based on requirements.',
    features: {
      matchmaking: true,
      leaderboards: true,
      cloudSave: true,
      analytics: true,
      multiplayer: true,
      serverless: false,
      authentication: true,
      chat: false,
      pushNotifications: true,
      inventory: true,
      economy: true,
      tournaments: true,
    },
    useCases: ['mobile', 'social', 'casual'],
    platforms: ['unity', 'custom'],
    pros: [
      'Purpose-built for live service games',
      'Strong economy and player management',
      'Highly customizable',
      'Good documentation and support',
      'Built-in admin dashboard',
    ],
    cons: [
      'Enterprise pricing may not suit small indies',
      'Smaller community compared to bigger platforms',
      'Limited engine support outside Unity',
    ],
    rating: 4.1,
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
  {
    slug: 'nakama',
    name: 'Nakama',
    tagline: 'Open-source scalable game server',
    description: 'Nakama is an open-source distributed game server that handles authentication, social features, storage, and real-time multiplayer. Built by Heroic Labs, it can be self-hosted or used via their managed cloud service.',
    logo: '/images/nakama.svg',
    website: 'https://heroiclabs.com/nakama/',
    docsUrl: 'https://heroiclabs.com/docs/nakama/',
    githubUrl: 'https://github.com/heroiclabs/nakama',
    type: 'open-source',
    pricingModel: 'freemium',
    pricingDetails: 'Open source for self-hosting. Managed cloud starts at $50/mo.',
    features: {
      matchmaking: true,
      leaderboards: true,
      cloudSave: true,
      analytics: false,
      multiplayer: true,
      serverless: true,
      authentication: true,
      chat: true,
      pushNotifications: true,
      inventory: true,
      economy: true,
      tournaments: true,
    },
    useCases: ['indie', 'mobile', 'competitive', 'casual'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    pros: [
      'Open source with active development',
      'Feature-rich out of the box',
      'Great SDK support across platforms',
      'Can self-host for full control',
      'Strong real-time capabilities',
    ],
    cons: [
      'Self-hosting requires DevOps knowledge',
      'Managed cloud pricing can add up',
      'Less enterprise features than commercial alternatives',
    ],
    rating: 4.4,
    foundedYear: 2017,
    lastUpdated: '2025-01',
  },
  {
    slug: 'colyseus',
    name: 'Colyseus',
    tagline: 'Multiplayer game server for Node.js',
    description: 'Colyseus is an authoritative multiplayer game server framework for Node.js. It provides state synchronization, matchmaking, and room-based multiplayer with a focus on simplicity and developer experience.',
    logo: '/images/colyseus.svg',
    website: 'https://colyseus.io',
    docsUrl: 'https://docs.colyseus.io',
    githubUrl: 'https://github.com/colyseus/colyseus',
    type: 'open-source',
    pricingModel: 'free',
    pricingDetails: 'Free and open source. Colyseus Arena offers managed hosting.',
    features: {
      matchmaking: true,
      leaderboards: false,
      cloudSave: false,
      analytics: false,
      multiplayer: true,
      serverless: false,
      authentication: true,
      chat: true,
      pushNotifications: false,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['indie', 'casual', 'competitive'],
    platforms: ['unity', 'custom', 'html5'],
    pros: [
      'Easy to learn and use',
      'Excellent state synchronization',
      'Active community and development',
      'Great for rapid prototyping',
      'Full control over server logic',
    ],
    cons: [
      'Node.js only (no other runtimes)',
      'Limited built-in features compared to platforms',
      'Scaling requires additional infrastructure',
    ],
    rating: 4.2,
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
  {
    slug: 'mirror',
    name: 'Mirror',
    tagline: 'High-level networking library for Unity',
    description: 'Mirror is an open-source networking library for Unity that evolved from the deprecated UNET. It provides a simple API for multiplayer games with support for various transports and is completely free to use.',
    logo: '/images/mirror.svg',
    website: 'https://mirror-networking.com',
    docsUrl: 'https://mirror-networking.gitbook.io/docs/',
    githubUrl: 'https://github.com/MirrorNetworking/Mirror',
    type: 'open-source',
    pricingModel: 'free',
    pricingDetails: 'Completely free and open source.',
    features: {
      matchmaking: false,
      leaderboards: false,
      cloudSave: false,
      analytics: false,
      multiplayer: true,
      serverless: false,
      authentication: false,
      chat: false,
      pushNotifications: false,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['indie', 'competitive'],
    platforms: ['unity'],
    pros: [
      'Completely free',
      'Active and helpful community',
      'Drop-in UNET replacement',
      'Multiple transport options',
      'Well-documented',
    ],
    cons: [
      'Unity-only',
      'No backend services included',
      'Requires own server hosting',
      'Learning curve for networking concepts',
    ],
    rating: 4.1,
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
  {
    slug: 'agones',
    name: 'Agones',
    tagline: 'Host, run, and scale dedicated game servers on Kubernetes',
    description: 'Agones is an open-source project by Google for hosting and scaling dedicated game servers on Kubernetes. It provides game server management, fleet scaling, and allocation capabilities for any game engine.',
    logo: '/images/agones.svg',
    website: 'https://agones.dev',
    docsUrl: 'https://agones.dev/site/docs/',
    githubUrl: 'https://github.com/googleforgames/agones',
    type: 'open-source',
    pricingModel: 'free',
    pricingDetails: 'Free and open source. You pay for your Kubernetes infrastructure.',
    features: {
      matchmaking: false,
      leaderboards: false,
      cloudSave: false,
      analytics: false,
      multiplayer: true,
      serverless: false,
      authentication: false,
      chat: false,
      pushNotifications: false,
      inventory: false,
      economy: false,
      tournaments: false,
    },
    useCases: ['mmo', 'competitive'],
    platforms: ['unity', 'unreal', 'custom'],
    pros: [
      'Cloud-agnostic Kubernetes solution',
      'Excellent auto-scaling',
      'Backed by Google',
      'Works with any game server',
      'Strong community support',
    ],
    cons: [
      'Requires Kubernetes expertise',
      'Only handles server orchestration',
      'Steep learning curve',
      'Overkill for small projects',
    ],
    rating: 4.0,
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
];

export const categories: Category[] = [
  {
    slug: 'mmo',
    name: 'MMO Games',
    description: 'Backends suitable for massively multiplayer online games requiring high scalability and persistence.',
    useCases: ['mmo'],
  },
  {
    slug: 'mobile',
    name: 'Mobile Games',
    description: 'Solutions optimized for mobile gaming with features like cloud save, analytics, and push notifications.',
    useCases: ['mobile'],
  },
  {
    slug: 'indie',
    name: 'Indie Games',
    description: 'Cost-effective options for independent developers with free tiers and easy setup.',
    useCases: ['indie'],
  },
  {
    slug: 'competitive',
    name: 'Competitive Games',
    description: 'Backends with strong matchmaking, anti-cheat support, and low-latency requirements.',
    useCases: ['competitive'],
  },
  {
    slug: 'casual',
    name: 'Casual Games',
    description: 'Simple, easy-to-integrate solutions for casual and social games.',
    useCases: ['casual'],
  },
];

export function getBackendBySlug(slug: string): Backend | undefined {
  return backends.find(b => b.slug === slug);
}

export function getBackendsByUseCase(useCase: UseCase): Backend[] {
  return backends.filter(b => b.useCases.includes(useCase));
}

export function getBackendsByType(type: Backend['type']): Backend[] {
  return backends.filter(b => b.type === type);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug);
}

export function getAllSlugs(): string[] {
  return backends.map(b => b.slug);
}

export const featureLabels: Record<keyof Backend['features'], string> = {
  matchmaking: 'Matchmaking',
  leaderboards: 'Leaderboards',
  cloudSave: 'Cloud Save',
  analytics: 'Analytics',
  multiplayer: 'Multiplayer',
  serverless: 'Serverless Functions',
  authentication: 'Authentication',
  chat: 'Chat',
  pushNotifications: 'Push Notifications',
  inventory: 'Inventory',
  economy: 'Virtual Economy',
  tournaments: 'Tournaments',
};

export const typeLabels: Record<Backend['type'], string> = {
  'commercial': 'Commercial',
  'open-source': 'Open Source',
  'hybrid': 'Hybrid',
};

export const pricingLabels: Record<Backend['pricingModel'], string> = {
  'free': 'Free',
  'freemium': 'Freemium',
  'paid': 'Paid',
  'enterprise': 'Enterprise',
};
