import { Backend, Category, GameType, LiveOpsFeatures } from './types';

export type { Backend, Category, GameType, LiveOpsFeatures } from './types';

export const backends: Backend[] = [
  {
    slug: 'metaplay',
    name: 'Metaplay',
    tagline: 'Purpose-built backend platform for live service games',
    description: 'Metaplay is a comprehensive game backend platform specifically designed for live service games. It provides a complete suite of tools for player management, live operations, game economy, and analytics - everything studios need to run successful games-as-a-service. Built by game industry veterans, Metaplay emphasizes both developer experience and operational excellence.',
    logo: '/images/metaplay.svg',
    website: 'https://metaplay.io',
    docsUrl: 'https://docs.metaplay.io',
    type: 'full-platform',
    pricingModel: 'enterprise',
    pricingDetails: 'Custom pricing based on game requirements and scale.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['F2P mobile games', 'Live service RPGs', 'Strategy games', 'Games with complex economies'],
    gameTypes: ['f2p-mobile', 'live-service-pc', 'casual-social'],
    platforms: ['unity', 'custom'],
    strengths: [
      'Purpose-built for live service game operations',
      'Comprehensive game economy and monetization tools',
      'Built-in admin dashboard for live ops teams',
      'Strong player segmentation and targeting',
      'Designed for long-term game operation',
    ],
    limitations: [
      'Enterprise-focused pricing model',
      'Unity-centric SDK ecosystem',
      'Not designed for real-time competitive multiplayer',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
  {
    slug: 'playfab',
    name: 'PlayFab',
    tagline: 'Microsoft\'s backend platform for live games',
    description: 'PlayFab is a comprehensive backend platform for building and operating live games, now part of Microsoft\'s Azure Gaming ecosystem. It offers a wide range of services from player authentication to live ops and analytics, with deep integration into Azure cloud services.',
    logo: '/images/playfab.svg',
    website: 'https://playfab.com',
    docsUrl: 'https://learn.microsoft.com/en-us/gaming/playfab/',
    type: 'full-platform',
    pricingModel: 'usage-based',
    pricingDetails: 'Free tier up to 100K MAU. Pay-as-you-go pricing above with volume discounts.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: false,
    },
    bestFor: ['Indie to mid-size studios', 'Xbox/PC games', 'Studios already in Azure ecosystem'],
    gameTypes: ['f2p-mobile', 'live-service-pc', 'competitive', 'casual-social'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    strengths: [
      'Generous free tier for smaller games',
      'Deep Azure and Xbox integration',
      'Broad SDK support across engines',
      'Extensive documentation',
      'Multiplayer server hosting included',
    ],
    limitations: [
      'Analytics can require Azure integration for advanced use',
      'Some features require Azure expertise',
      'Support responsiveness varies by tier',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'nakama',
    name: 'Nakama',
    tagline: 'Open-source scalable game server',
    description: 'Nakama is an open-source distributed game server by Heroic Labs that handles authentication, social features, storage, and real-time multiplayer. It can be self-hosted or used via their managed cloud service, offering flexibility for studios that want control over their infrastructure.',
    logo: '/images/nakama.svg',
    website: 'https://heroiclabs.com/nakama/',
    docsUrl: 'https://heroiclabs.com/docs/nakama/',
    githubUrl: 'https://github.com/heroiclabs/nakama',
    type: 'open-source',
    pricingModel: 'freemium',
    pricingDetails: 'Open source for self-hosting. Managed cloud service available with tiered pricing.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: true,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: false,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: true,
      analytics: false,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Studios wanting infrastructure control', 'Real-time multiplayer games', 'Teams with DevOps capability'],
    gameTypes: ['competitive', 'casual-social', 'f2p-mobile'],
    platforms: ['unity', 'unreal', 'godot', 'custom', 'html5'],
    strengths: [
      'Open source with active development',
      'Strong real-time multiplayer capabilities',
      'Flexible self-hosting or managed options',
      'Good SDK support across platforms',
      'Active community',
    ],
    limitations: [
      'Limited built-in live ops tooling',
      'No native analytics or A/B testing',
      'Self-hosting requires DevOps expertise',
      'Live service features require custom development',
    ],
    liveServiceFit: 'partial',
    foundedYear: 2017,
    lastUpdated: '2025-01',
  },
  {
    slug: 'aws-gamelift',
    name: 'AWS GameLift',
    tagline: 'Dedicated game server hosting from Amazon',
    description: 'Amazon GameLift is a dedicated game server hosting solution that deploys, operates, and scales cloud servers for multiplayer games. It focuses on session-based multiplayer with FlexMatch for matchmaking, integrating with the broader AWS ecosystem.',
    logo: '/images/gamelift.svg',
    website: 'https://aws.amazon.com/gamelift/',
    docsUrl: 'https://docs.aws.amazon.com/gamelift/',
    type: 'partial-solution',
    pricingModel: 'usage-based',
    pricingDetails: 'Pay per instance hour. FlexMatch and other services priced separately.',
    features: {
      authentication: false,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Session-based multiplayer', 'Games needing dedicated servers', 'Studios in AWS ecosystem'],
    gameTypes: ['competitive', 'mmo'],
    platforms: ['unity', 'unreal', 'custom'],
    strengths: [
      'Enterprise-grade server infrastructure',
      'Excellent auto-scaling for player demand',
      'FlexMatch offers flexible matchmaking',
      'Global presence across AWS regions',
      'Deep AWS service integration',
    ],
    limitations: [
      'Server hosting only - not a complete backend',
      'Requires building other live service features separately',
      'Steep learning curve for AWS newcomers',
      'No player management or economy features',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2016,
    lastUpdated: '2025-01',
  },
  {
    slug: 'photon-engine',
    name: 'Photon Engine',
    tagline: 'Real-time multiplayer networking platform',
    description: 'Photon is a suite of products for real-time multiplayer games, including Photon Cloud, Photon Server, and Photon Fusion. It focuses on networking and synchronization, providing reliable real-time communication for games.',
    logo: '/images/photon.svg',
    website: 'https://www.photonengine.com',
    docsUrl: 'https://doc.photonengine.com',
    type: 'partial-solution',
    pricingModel: 'usage-based',
    pricingDetails: 'Free tier with 20 CCU. Subscription plans based on concurrent users.',
    features: {
      authentication: true,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Real-time multiplayer games', 'Unity developers', 'Games needing low-latency networking'],
    gameTypes: ['competitive', 'casual-social'],
    platforms: ['unity', 'unreal', 'custom', 'html5'],
    strengths: [
      'Industry-leading real-time networking',
      'Excellent Unity integration',
      'Photon Fusion for advanced networking',
      'Reliable global infrastructure',
      'Well-documented with tutorials',
    ],
    limitations: [
      'Networking only - no backend features',
      'CCU-based pricing can be unpredictable',
      'Requires separate solutions for live ops',
      'No player data or economy management',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2004,
    lastUpdated: '2025-01',
  },
  {
    slug: 'unity-gaming-services',
    name: 'Unity Gaming Services',
    tagline: 'Backend services integrated into Unity',
    description: 'Unity Gaming Services (UGS) is Unity\'s suite of backend services built directly into the Unity ecosystem. It provides authentication, cloud save, economy, analytics, and more with tight editor integration for Unity developers.',
    logo: '/images/unity.svg',
    website: 'https://unity.com/solutions/gaming-services',
    docsUrl: 'https://docs.unity.com/ugs/',
    type: 'full-platform',
    pricingModel: 'usage-based',
    pricingDetails: 'Free tier available. Usage-based pricing for higher volumes.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: false,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: false,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: false,
      pushNotifications: true,
      leaderboards: true,
      achievements: false,
      socialFeatures: true,
      guildsClans: false,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: false,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Unity-only studios', 'Teams wanting tight editor integration', 'Rapid prototyping'],
    gameTypes: ['f2p-mobile', 'casual-social', 'competitive'],
    platforms: ['unity'],
    strengths: [
      'Seamless Unity editor integration',
      'Unified dashboard for all services',
      'Good analytics and A/B testing',
      'Economy system included',
      'Active development and expansion',
    ],
    limitations: [
      'Unity-only - no other engine support',
      'Some services still maturing',
      'Less flexibility than standalone solutions',
      'Vendor lock-in to Unity ecosystem',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2021,
    lastUpdated: '2025-01',
  },
  {
    slug: 'colyseus',
    name: 'Colyseus',
    tagline: 'Multiplayer game server framework for Node.js',
    description: 'Colyseus is an authoritative multiplayer game server framework for Node.js. It provides state synchronization, matchmaking, and room-based multiplayer with a focus on simplicity and developer experience for building real-time games.',
    logo: '/images/colyseus.svg',
    website: 'https://colyseus.io',
    docsUrl: 'https://docs.colyseus.io',
    githubUrl: 'https://github.com/colyseus/colyseus',
    type: 'open-source',
    pricingModel: 'free',
    pricingDetails: 'Free and open source. Colyseus Arena offers managed hosting.',
    features: {
      authentication: true,
      playerProfiles: false,
      playerSegmentation: false,
      liveEvents: false,
      seasonalContent: false,
      remoteConfig: false,
      abTesting: false,
      scheduledContent: false,
      virtualCurrency: false,
      inventorySystem: false,
      iapValidation: false,
      offers: false,
      pushNotifications: false,
      leaderboards: false,
      achievements: false,
      socialFeatures: false,
      guildsClans: false,
      analytics: false,
      playerBehaviorTracking: false,
      revenueAnalytics: false,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: false,
      serverlessLogic: false,
      dedicatedServers: false,
      globalScaling: false,
      adminDashboard: false,
      playerSupport: false,
      moderation: false,
    },
    bestFor: ['Indie developers', 'Rapid multiplayer prototyping', 'Node.js developers'],
    gameTypes: ['casual-social', 'competitive'],
    platforms: ['unity', 'custom', 'html5'],
    strengths: [
      'Easy to learn and quick to prototype',
      'Excellent state synchronization',
      'Active open-source community',
      'Full control over server logic',
      'Free to use',
    ],
    limitations: [
      'Multiplayer framework only - no backend features',
      'Node.js runtime required',
      'Scaling requires additional infrastructure work',
      'No live ops, analytics, or economy features',
    ],
    liveServiceFit: 'minimal',
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
  {
    slug: 'braincloud',
    name: 'brainCloud',
    tagline: 'Backend-as-a-service for games',
    description: 'brainCloud is a ready-made backend platform for games that provides a comprehensive set of cloud features including player management, cloud data, leaderboards, and multiplayer support with a focus on mobile and casual games.',
    logo: '/images/braincloud.svg',
    website: 'https://getbraincloud.com',
    docsUrl: 'https://docs.braincloudservers.com',
    type: 'full-platform',
    pricingModel: 'freemium',
    pricingDetails: 'Free development tier. Production pricing based on DAU.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: false,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: false,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: false,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['Mobile games', 'Casual games', 'Small to mid-size studios'],
    gameTypes: ['f2p-mobile', 'casual-social'],
    platforms: ['unity', 'unreal', 'custom'],
    strengths: [
      'Comprehensive feature set',
      'Good for mobile game development',
      'Achievements and gamification built-in',
      'Reasonable pricing for smaller games',
      'Long-established platform',
    ],
    limitations: [
      'Less common in larger productions',
      'Smaller community than major platforms',
      'Documentation can be dated in places',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2014,
    lastUpdated: '2025-01',
  },
  {
    slug: 'accelbyte',
    name: 'AccelByte',
    tagline: 'Backend platform for AAA live service games',
    description: 'AccelByte provides a comprehensive backend platform targeting AAA and large-scale live service games. It offers player identity, social features, e-commerce, game services, and analytics designed for high-scale productions.',
    logo: '/images/accelbyte.svg',
    website: 'https://accelbyte.io',
    docsUrl: 'https://docs.accelbyte.io',
    type: 'full-platform',
    pricingModel: 'enterprise',
    pricingDetails: 'Enterprise pricing. Contact for quotes.',
    features: {
      authentication: true,
      playerProfiles: true,
      playerSegmentation: true,
      liveEvents: true,
      seasonalContent: true,
      remoteConfig: true,
      abTesting: true,
      scheduledContent: true,
      virtualCurrency: true,
      inventorySystem: true,
      iapValidation: true,
      offers: true,
      pushNotifications: true,
      leaderboards: true,
      achievements: true,
      socialFeatures: true,
      guildsClans: true,
      analytics: true,
      playerBehaviorTracking: true,
      revenueAnalytics: true,
      customDashboards: true,
      multiplayer: true,
      matchmaking: true,
      chat: true,
      cloudSave: true,
      serverlessLogic: true,
      dedicatedServers: true,
      globalScaling: true,
      adminDashboard: true,
      playerSupport: true,
      moderation: true,
    },
    bestFor: ['AAA studios', 'Large-scale live service games', 'Cross-platform titles'],
    gameTypes: ['live-service-pc', 'competitive', 'mmo'],
    platforms: ['unity', 'unreal', 'custom'],
    strengths: [
      'Built for AAA scale',
      'Comprehensive feature coverage',
      'Strong e-commerce and monetization',
      'Cross-platform support',
      'Enterprise-grade infrastructure',
    ],
    limitations: [
      'Enterprise pricing not suited for indies',
      'Complex integration for smaller projects',
      'Requires significant implementation effort',
    ],
    liveServiceFit: 'comprehensive',
    foundedYear: 2018,
    lastUpdated: '2025-01',
  },
];

export const categories: Category[] = [
  {
    slug: 'f2p-mobile',
    name: 'F2P Mobile Games',
    description: 'Free-to-play mobile games that rely on live ops, events, and monetization to drive revenue and retention.',
    gameTypes: ['f2p-mobile'],
  },
  {
    slug: 'live-service-pc',
    name: 'Live Service PC/Console',
    description: 'PC and console games operated as ongoing services with regular content updates and seasonal events.',
    gameTypes: ['live-service-pc'],
  },
  {
    slug: 'competitive',
    name: 'Competitive Multiplayer',
    description: 'Competitive games requiring real-time multiplayer, matchmaking, and ranking systems.',
    gameTypes: ['competitive'],
  },
  {
    slug: 'casual-social',
    name: 'Casual & Social Games',
    description: 'Casual games with social features, leaderboards, and lighter live ops requirements.',
    gameTypes: ['casual-social'],
  },
  {
    slug: 'mmo',
    name: 'MMO & Persistent Worlds',
    description: 'Massively multiplayer games requiring large-scale infrastructure and persistent world states.',
    gameTypes: ['mmo'],
  },
];

export const educationalContent = [
  {
    slug: 'what-is-live-service',
    title: 'What is a Live Service Game?',
    description: 'Understanding the live service model and why it dominates modern game development.',
    order: 1,
  },
  {
    slug: 'pillars-of-live-ops',
    title: 'Pillars of Live Operations',
    description: 'The core capabilities every live service game needs to succeed.',
    order: 2,
  },
  {
    slug: 'retention-engagement',
    title: 'Retention & Engagement',
    description: 'Strategies and features that keep players coming back day after day.',
    order: 3,
  },
  {
    slug: 'monetization-economy',
    title: 'Monetization & Game Economy',
    description: 'Building sustainable revenue through virtual economies and in-app purchases.',
    order: 4,
  },
  {
    slug: 'analytics-optimization',
    title: 'Analytics & Optimization',
    description: 'Using data to understand player behavior and optimize your game.',
    order: 5,
  },
];

export function getBackendBySlug(slug: string): Backend | undefined {
  return backends.find(b => b.slug === slug);
}

export function getBackendsByGameType(gameType: GameType): Backend[] {
  return backends.filter(b => b.gameTypes.includes(gameType));
}

export function getBackendsByType(type: Backend['type']): Backend[] {
  return backends.filter(b => b.type === type);
}

export function getBackendsByLiveServiceFit(fit: Backend['liveServiceFit']): Backend[] {
  return backends.filter(b => b.liveServiceFit === fit);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug);
}

export function getAllSlugs(): string[] {
  return backends.map(b => b.slug);
}

export const featureCategories = {
  'Player Management': ['authentication', 'playerProfiles', 'playerSegmentation'],
  'Live Operations': ['liveEvents', 'seasonalContent', 'remoteConfig', 'abTesting', 'scheduledContent'],
  'Economy & Monetization': ['virtualCurrency', 'inventorySystem', 'iapValidation', 'offers'],
  'Engagement & Retention': ['pushNotifications', 'leaderboards', 'achievements', 'socialFeatures', 'guildsClans'],
  'Analytics & Insights': ['analytics', 'playerBehaviorTracking', 'revenueAnalytics', 'customDashboards'],
  'Multiplayer & Real-time': ['multiplayer', 'matchmaking', 'chat'],
  'Infrastructure': ['cloudSave', 'serverlessLogic', 'dedicatedServers', 'globalScaling'],
  'Operations': ['adminDashboard', 'playerSupport', 'moderation'],
};

export const featureLabels: Record<keyof LiveOpsFeatures, string> = {
  authentication: 'Authentication',
  playerProfiles: 'Player Profiles',
  playerSegmentation: 'Player Segmentation',
  liveEvents: 'Live Events',
  seasonalContent: 'Seasonal Content',
  remoteConfig: 'Remote Config',
  abTesting: 'A/B Testing',
  scheduledContent: 'Scheduled Content',
  virtualCurrency: 'Virtual Currency',
  inventorySystem: 'Inventory System',
  iapValidation: 'IAP Validation',
  offers: 'Targeted Offers',
  pushNotifications: 'Push Notifications',
  leaderboards: 'Leaderboards',
  achievements: 'Achievements',
  socialFeatures: 'Social Features',
  guildsClans: 'Guilds/Clans',
  analytics: 'Analytics',
  playerBehaviorTracking: 'Behavior Tracking',
  revenueAnalytics: 'Revenue Analytics',
  customDashboards: 'Custom Dashboards',
  multiplayer: 'Multiplayer',
  matchmaking: 'Matchmaking',
  chat: 'Chat',
  cloudSave: 'Cloud Save',
  serverlessLogic: 'Serverless Logic',
  dedicatedServers: 'Dedicated Servers',
  globalScaling: 'Global Scaling',
  adminDashboard: 'Admin Dashboard',
  playerSupport: 'Player Support Tools',
  moderation: 'Moderation',
};

export const typeLabels: Record<Backend['type'], string> = {
  'full-platform': 'Full Platform',
  'partial-solution': 'Partial Solution',
  'open-source': 'Open Source',
};

export const pricingLabels: Record<Backend['pricingModel'], string> = {
  'free': 'Free',
  'freemium': 'Freemium',
  'usage-based': 'Usage-Based',
  'enterprise': 'Enterprise',
};

export const liveServiceFitLabels: Record<Backend['liveServiceFit'], string> = {
  'comprehensive': 'Comprehensive',
  'partial': 'Partial Coverage',
  'minimal': 'Networking Only',
};
